# Generated by Django 2.1.3 on 2019-03-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_education_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.CharField(default='this is my url', max_length=300),
            preserve_default=False,
        ),
    ]
